version: '3.8'
services:
  redis-pic-container:
    image: redis:alpine
    networks:
      - pic-net
    ports:
      - 6380:6379

  mysql-pic-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pic_db
    networks:
      - pic-net
    ports:
      - 3307:3306

  pic-backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - redis-pic-container
      - mysql-pic-container
    networks:
      - pic-net

networks:
  pic-net:
    driver: bridge
